#http端口号
server:
  port: 8001

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://www.fatesgo.com:3301/fatesgo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
# 打印sql
#logging:
#  level:
#        com.fatesgo.admin.api.mapper: debug
  # redis 配置
  redis:
    # 地址
    host: www.fatesgo.com
    # 端口，默认为6379/3300
    port: 3300
    # 密码
    password: Hwj+147258
    # 连接超时时间
    timeout: 60s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms






